version: "3.5"
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "l0"
      POSTGRES_USER: "userL0"
      POSTGRES_PASSWORD: "userL0"
    ports:
      - "8001:5432"
    restart: always
    volumes:
      - ./migrations/1_init.up.sql:/docker-entrypoint-initdb.d/init.sql
  nats:
    image: nats-streaming:latest
    ports:
      - "8222:8222"
      - "4222:4222"
